"""Non-agent CSV ingestion pipeline — Phase 0 exit criterion.

Usage:
    python3 scripts/ingest_csv.py <csv_path> <problem_uuid> <output_dir>

Produces:
    - PostgreSQL table: problem_{uuid_hex} with CSV data
    - {output_dir}/app.py: trivial Streamlit app showing the data
"""
__pattern__ = "TemplateMethod"

import argparse
import csv
import pathlib
import re
import sys
from typing import Any


def _sanitize_name(name: str) -> str:
    """Convert a string to a safe SQL identifier."""
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_") or "col"


def ingest_csv(
    csv_path: str,
    problem_uuid: str,
    output_dir: str,
    db_url: str | None = None,
) -> dict[str, Any]:
    """Template Method: fixed steps, overrideable internals.

    Steps:
    1. Read CSV and infer column types
    2. Create PostgreSQL table
    3. Load all rows
    4. Generate Streamlit app.py
    5. Return manifest
    """
    csv_file = pathlib.Path(csv_path)
    if not csv_file.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    out_dir = pathlib.Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: Read CSV
    with open(csv_file, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError("CSV has no header row")
        columns = [_sanitize_name(col) for col in reader.fieldnames]
        rows = list(reader)

    # Step 2 & 3: Load into PostgreSQL (if db_url provided)
    table_name = f"problem_{problem_uuid.replace('-', '_')}"
    rows_loaded = 0
    if db_url:
        rows_loaded = _load_to_postgres(table_name, columns, rows, db_url)

    # Step 4: Generate Streamlit app.py
    app_path = out_dir / "app.py"
    _generate_app(app_path, table_name, columns, db_url or "")

    return {
        "table_name": table_name,
        "columns": columns,
        "rows_loaded": rows_loaded,
        "app_path": str(app_path),
    }


def _load_to_postgres(
    table_name: str,
    columns: list[str],
    rows: list[dict],
    db_url: str,
) -> int:
    """Create table and load rows. Returns row count."""
    try:
        import psycopg2
    except ImportError:
        print("[ingest_csv] psycopg2 not installed; skipping DB load", file=sys.stderr)
        return 0

    col_defs = ", ".join(f'"{col}" TEXT' for col in columns)
    ddl = f'CREATE TABLE IF NOT EXISTS "{table_name}" ({col_defs})'

    conn = psycopg2.connect(db_url)
    try:
        with conn.cursor() as cur:
            cur.execute(ddl)
            if rows:
                placeholders = ", ".join(["%s"] * len(columns))
                insert_sql = f'INSERT INTO "{table_name}" VALUES ({placeholders})'
                values = [
                    tuple(row.get(col, "") for col in row)
                    for row in rows
                ]
                cur.executemany(insert_sql, values)
        conn.commit()
        return len(rows)
    finally:
        conn.close()


def _generate_app(
    app_path: pathlib.Path,
    table_name: str,
    columns: list[str],
    db_url: str,
) -> None:
    """Generate a trivial Streamlit app that shows the ingested data."""
    app_code = f'''"""OAK Phase 0 — Auto-generated Streamlit app for {table_name}."""
import streamlit as st
import pandas as pd

DB_URL = "{db_url}" or "postgresql://oak:oak@localhost:5432/oak"

st.title("OAK · {table_name}")
st.caption("Auto-generated by OAK Phase 0 non-agent pipeline.")

try:
    import psycopg2
    conn = psycopg2.connect(DB_URL)
    df = pd.read_sql('SELECT * FROM "{table_name}" LIMIT 1000', conn)
    conn.close()
    st.dataframe(df, use_container_width=True)
    st.metric("Rows loaded", len(df))
except Exception as e:
    st.error(f"Could not connect to database: {{e}}")
    st.info("Ensure the OAK stack is running: docker compose up")
'''
    app_path.write_text(app_code)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="OAK Phase 0 CSV ingestion")
    parser.add_argument("csv_path", help="Path to CSV file")
    parser.add_argument("problem_uuid", help="Problem UUID")
    parser.add_argument("output_dir", help="Output directory for app.py")
    parser.add_argument("--db-url", default=None, help="PostgreSQL connection URL")
    args = parser.parse_args()

    from api.config import settings

    db_url = args.db_url or settings.database_url

    result = ingest_csv(args.csv_path, args.problem_uuid, args.output_dir, db_url)
    print(
        f"[ingest_csv] Done: table={result['table_name']} "
        f"rows={result['rows_loaded']} app={result['app_path']}"
    )
